kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: quay-demo
networking:
  apiServerPort: 6443
  apiServerAddress: 127.0.0.1
  podSubnet: "10.245.0.0/16"
  serviceSubnet: "10.23.0.0/16"
nodes:
- role: control-plane
  image: docker.io/kindest/node:v1.26.0
  extraPortMappings:
  - containerPort: 32042
    hostPort: 42042
    listenAddress: 0.0.0.0
  - containerPort: 31234
    hostPort: 41234
    listenAddress: 0.0.0.0
  - containerPort: 31235
    hostPort: 41235
    listenAddress: 0.0.0.0
  - containerPort: 80
    hostPort: 80
    listenAddress: 0.0.0.0
  - containerPort: 443
    hostPort: 443
    listenAddress: 0.0.0.0
- role: worker
  image: docker.io/kindest/node:v1.26.0
- role: worker
  image: docker.io/kindest/node:v1.26.0
