apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: extra-cert-pusher
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: extra-cert-reader
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["list", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: extra-cert-pusher
  namespace: quay
subjects:
- kind: ServiceAccount
  name: extra-cert-pusher
  namespace: quay
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: extra-cert-pusher
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: extra-cert-reader
  namespace: istio-system
subjects:
- kind: ServiceAccount
  name: extra-cert-pusher
  namespace: quay
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: extra-cert-reader
---
