apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- namespace.yml
- ingress.yml
- provisioning.yml

images:
- name: localhost/grafana
  newName: docker.io/grafana/grafana
  newTag: latest
