{
 "title": "Quay Monitoring",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "quay", "label": "quay instance", "query": { "query": "go_info" } },
   { "name": "clair", "label": "clair instance", "query": { "query": "go_info" } },
   { "name": "quayjob", "label": "quay job", "query": { "query": "go_info" } },
   { "name": "clairjob", "label": "clair job", "query": { "query": "go_info" } }
  ]
 },
 "panels": [
  {
   "title": "Repositories/Scanned",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(quay_repository_rows{instance=\"$quay\", job=\"$quayjob\"}) OR on() vector(0)",
     "legendFormat": "total"
    },
    {
     "expr": "sum(quay_security_scanning_unscanned_images_remaining{instance=\"$quay\", job=\"$quayjob\"}) OR on() vector(0)",
     "legendFormat": "unscanned"
    },
    {
     "expr": "sum(quay_repository_rows_unmirrored{instance=\"$quay\", job=\"$quayjob\"}) OR on() vector(0)",
     "legendFormat": "unmirrored"
    }
   ]
  },
  {
   "title": "Stats",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(quay_user_rows{instance=\"$quay\", job=\"$quayjob\"}) OR on() vector(0)",
     "legendFormat": "Users"
    },
    {
     "expr": "sum(quay_org_rows{instance=\"$quay\", job=\"$quayjob\"}) OR on() vector(0)",
     "legendFormat": "Organizations"
    },
    {
     "expr": "sum(quay_robot_rows{instance=\"$quay\", job=\"$quayjob\"}) OR on() vector(0)",
     "legendFormat": "Robots"
    },
    {
     "expr": "sum(quay_repository_rows{instance=\"$quay\", job=\"$quayjob\"}) OR on() vector(0)",
     "legendFormat": "Repositories"
    }
   ]
  },
  {
   "title": "Pull/Push statistics",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 5, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (status) ( rate(quay_registry_image_pulls_total{instance=\"$quay\",job=\"$quayjob\"}[5m]) )",
     "legendFormat": "pull"
    },
    {
     "expr": "sum by (status) ( rate(quay_registry_image_push_total{instance=\"$quay\",job=\"$quayjob\"}[5m]) )",
     "legendFormat": "push"
    }
   ]
  },
  {
   "title": "Database Statistics total/close calls",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 4, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (process_name) ( rate(quay_db_connect_calls_total{instance=\"$quay\",job=\"$quayjob\"}[5m]) )",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "sum by (process_name) ( rate(quay_db_close_calls_total{instance=\"$quay\",job=\"$quayjob\"}[5m]) )",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Authentication attempts",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (process_name, success) ( rate(quay_authentication_attempts_total{instance=\"$quay\",job=\"$quayjob\"}[5m]))",
     "legendFormat": "{{process_name}} {{success}}"
    },
    {
     "expr": "sum by (status, process_name) ( rate (quay_request_duration_seconds_count{instance=\"$quay\", job=\"$quayjob\"}[5m]))",
     "legendFormat": "{{process_name}} {{status}}"
    }
   ]
  },
  {
   "title": "Chunk/Multipart Upload statistics",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum( rate(quay_chunk_upload_duration_seconds_count{instance=\"$quay\",job=\"$quayjob\"}[5m])) OR on() vector(0)",
     "legendFormat": "chunk durations seconds"
    },
    {
     "expr": "sum( rate(quay_multipart_uploads_completed_total{instance=\"$quay\",job=\"$quayjob\"}[5m])) OR on() vector(0)",
     "legendFormat": "multiparts total"
    }
   ]
  },
  {
   "title": "Image push/pull bytes",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum ( rate(quay_registry_image_pulled_estimated_bytes_total{instance=\"$quay\",job=\"$quayjob\"}[5m]))  OR on() vector(0)",
     "legendFormat": "pull"
    },
    {
     "expr": "sum ( rate(quay_registry_image_pushed_bytes_total{instance=\"$quay\",job=\"$quayjob\"}[5m]))  OR on() vector(0)",
     "legendFormat": "push"
    }
   ]
  },
  {
   "title": "Work Queue",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(quay_queue_item_gets_total{instance=\"$quay\", job=\"$quayjob\"}[5m])) OR on() vector(0)",
     "legendFormat": "total"
    },
    {
     "expr": "sum(rate(quay_queue_item_deletes_total{instance=\"$quay\", job=\"$quayjob\"}[5m])) OR on() vector(0)",
     "legendFormat": "deletes"
    },
    {
     "expr": "sum(rate(quay_queue_item_gets_total{instance=\"$quay\", job=\"$quayjob\"}[5m])) OR on() vector(0)",
     "legendFormat": "gets"
    },
    {
     "expr": "sum(rate(quay_queue_item_puts_total{instance=\"$quay\", job=\"$quayjob\"}[5m])) OR on() vector(0)",
     "legendFormat": "puts"
    },
    {
     "expr": "sum(rate(quay_queue_items_available{instance=\"$quay\", job=\"$quayjob\"}[5m])) OR on() vector(0)",
     "legendFormat": "available"
    }
   ]
  },
  {
   "title": "Quay health state",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(quay_health_status{status_code=\"200\"})",
     "legendFormat": "healthy"
    },
    {
     "expr": "sum(quay_health_status{status_code=\"503\"}) or vector(0)",
     "legendFormat": "failure"
    }
   ]
  },
  {
   "title": "Clair HTTP response codes",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 3, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sort ( rate(promhttp_metric_handler_requests_total{instance=\"$clair\",job=\"$clairjob\"}[5m]) )",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Connections (Indexer)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 4, "x": 3, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (application_name) (pgxpool_idle_conns{instance=\"$clair\",job=\"$clairjob\",application_name=\"libindex\"}) OR on() vector(0)",
     "legendFormat": "idle"
    },
    {
     "expr": "sum by (application_name) (pgxpool_max_conns{instance=\"$clair\",job=\"$clairjob\",application_name=\"libindex\"}) OR on() vector(0)",
     "legendFormat": "max"
    },
    {
     "expr": "sum by (application_name) (pgxpool_total_conns{instance=\"$clair\",job=\"$clairjob\",application_name=\"libindex\"}) OR on() vector(0)",
     "legendFormat": "total"
    },
    {
     "expr": "sum by (application_name) (pgxpool_acquired_conns{instance=\"$clair\",job=\"$clairjob\",application_name=\"libindex\"}) OR on() vector(0)",
     "legendFormat": "acquired"
    }
   ]
  },
  {
   "title": "Quay Database state",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 4, "x": 7, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(quay_db_pooled_connections_available{instance=\"$quay\",job=\"$quayjob\"}[5m])) OR on() vector(0)",
     "legendFormat": "total"
    },
    {
     "expr": "sum(avg_over_time(quay_db_pooled_connections_in_use{instance=\"$quay\",job=\"$quayjob\"}[5m])) OR on() vector(0)",
     "legendFormat": "in_use"
    },
    {
     "expr": "sum(rate(quay_db_connect_calls_total{instance=\"$quay\",job=\"$quayjob\"}[5m])) OR on() vector(0)",
     "legendFormat": "calls total"
    }
   ]
  },
  {
   "title": "Get vulnerabilities latency",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 4, "x": 11, "y": 12 },
   "targets": [
    {
     "expr": "sum(rate(claircore_vulnstore_getvulnerabilities_duration_seconds_bucket{instance=\"$clair\",job=\"$clairjob\"}[5m])) by (le) OR on() vector(0)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Get update operations latency",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 4, "x": 15, "y": 12 },
   "targets": [
    {
     "expr": "sum(rate(claircore_vulnstore_getupdateoperations_duration_seconds_bucket{instance=\"$clair\",job=\"$clairjob\"}[5m])) by (le) OR on() vector(0)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Update vulnerabilities latency",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 12 },
   "targets": [
    {
     "expr": "sum(rate(claircore_vulnstore_updatevulnerabilities_duration_seconds_bucket{instance=\"$clair\",job=\"$clairjob\"}[5m])) by (le) ",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Set index_report query duration",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum(rate(claircore_indexer_setindexreport_duration_seconds_bucket{instance=\"$clair\",job=\"$clairjob\"}[5m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Layer scanned query duration",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 4, "x": 4, "y": 22 },
   "targets": [
    {
     "expr": "sum(rate(claircore_indexer_layerscanned_duration_seconds_bucket{instance=\"$clair\",job=\"$clairjob\"}[5m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Persist manifest query duration",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 4, "x": 8, "y": 22 },
   "targets": [
    {
     "expr": "sum(rate(claircore_indexer_persistmanifest_duration_seconds_bucket{instance=\"$clair\",job=\"$clairjob\"}[5m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Manifest scanned query duration",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 4, "x": 12, "y": 22 },
   "targets": [
    {
     "expr": "sum(rate(claircore_indexer_manifestscanned_duration_seconds_bucket{instance=\"$clair\",job=\"$clairjob\"}[5m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Register scanners query duration",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 4, "x": 16, "y": 22 },
   "targets": [
    {
     "expr": "sum(rate(claircore_indexer_registerscanners_duration_seconds_bucket{instance=\"$clair\",job=\"$clairjob\"}[5m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Set index finished query duration",
   "type": "heatmap",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 22 },
   "targets": [
    {
     "expr": "sum(rate(claircore_indexer_setindexfinished_duration_seconds_bucket{instance=\"$clair\",job=\"$clairjob\"}[5m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (job)(go_memstats_heap_inuse_bytes{instance=~\"($quay|$clair)\",job=~\"($quayjob|$clairjob)\"})",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Process CPU seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=\"$quay\",job=\"$quayjob\"}[5m])",
     "legendFormat": "{{process_name}}"
    }
   ]
  },
  {
   "title": "Create Index Report Request Latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 8, "x": 6, "y": 32 },
   "targets": [
    {
     "expr": "sum(increase(clair_http_indexerv1_request_duration_seconds_bucket{instance=\"$clair\",job=\"$clairjob\",method=\"post\", handler=\"/indexer/api/v1/index_report\", code=\"201\"} [5m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  },
  {
   "title": "Indexer State Request Latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 32 },
   "targets": [
    {
     "expr": "sum(increase(clair_http_indexerv1_request_duration_seconds_bucket{instance=\"$clair\",job=\"$clairjob\", method=\"get\", handler=\"/indexer/api/v1/index_state\"} [5m])) by (le)",
     "legendFormat": "{{ le }}"
    }
   ]
  }
 ]
}