apiVersion: v1
items:
- apiVersion: networking.istio.io/v1beta1
  kind: VirtualService
  metadata:
    name: minio
  spec:
    gateways:
    - istio-system/frontend-gateway
    hosts:
    - minio.example.com
    http:
    - match:
      - headers:
          User-Agent:
            prefix: Mozilla
      route:
      - destination:
          host: minio.quay.svc.cluster.local
          port:
            number: 9001
          subset: v1
        weight: 100
    - match:
      - uri:
          prefix: /
      route:
      - destination:
          host: minio.quay.svc.cluster.local
          port:
            number: 9000
          subset: v1
        weight: 100
- apiVersion: networking.istio.io/v1beta1
  kind: VirtualService
  metadata:
    name: minio-mesh
  spec:
    hosts:
    - minio.quay.svc
    - minio.quay.svc.cluster.local
    http:
    - match:
      - uri:
          prefix: /
      route:
      - destination:
          host: minio.quay.svc.cluster.local
          port:
            number: 9000
          subset: v1
        weight: 100
- apiVersion: networking.istio.io/v1beta1
  kind: DestinationRule
  metadata:
    name: minio
  spec:
    host: minio.quay.svc.cluster.local
    subsets:
    - labels:
        version: v1
      name: v1
    trafficPolicy:
      connectionPool:
        tcp:
          maxConnections: 100
          connectTimeout: 3s
          tcpKeepalive:
            time: 60s
            interval: 10s
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
