kind: DestinationRule
apiVersion: networking.istio.io/v1beta1
metadata:
  name: postgres
  namespace: quay
spec:
  host: postgres.quay.svc.cluster.local
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 100
        connectTimeout: 3s
        tcpKeepalive:
          time: 60s
          interval: 30s
