apiVersion: v1
items:
- apiVersion: networking.istio.io/v1beta1
  kind: VirtualService
  metadata:
    name: quay-mirror
  spec:
    gateways:
    - istio-system/frontend-gateway
    hosts:
    - quay-mirror.example.com
    http:
    - match:
      - uri:
          prefix: /metrics
      route:
      - destination:
          host: quay-mirror.quay.svc.cluster.local
          port:
            number: 9091
          subset: v1
        weight: 100
    - match:
      - headers:
          User-Agent:
            prefix: Mozilla
      route:
      - destination:
          host: quay-mirror.quay.svc.cluster.local
          port:
            number: 8080
          subset: v1
        weight: 100
    - match:
      - uri:
          prefix: /
      route:
      - destination:
          host: quay-mirror.quay.svc.cluster.local
          port:
            number: 8080
          subset: v1
        weight: 100
- apiVersion: networking.istio.io/v1beta1
  kind: DestinationRule
  metadata:
    name: quay-mirror
  spec:
    host: quay-mirror.quay.svc.cluster.local
    subsets:
    - labels:
        version: v1
      name: v1
    trafficPolicy:
      connectionPool:
        tcp:
          maxConnections: 100
          connectTimeout: 3s
          tcpKeepalive:
            time: 60s
            interval: 10s
        http:
          idleTimeout: 30s
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
