apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- metallb-native.yaml

images:
- name: localhost/controller
  newName: quay.io/metallb/controller
  newTag: v0.13.7
- name: localhost/speaker
  newName: quay.io/metallb/speaker
  newTag: v0.13.7

