apiVersion: v1
items:
- apiVersion: networking.istio.io/v1beta1
  kind: DestinationRule
  metadata:
    name: clairv4
    namespace: clair
  spec:
    host: clairv4.clair.svc.cluster.local
    subsets:
    - labels:
        version: v1
      name: v1
    trafficPolicy:
      connectionPool:
        tcp:
          maxConnections: 100
          connectTimeout: 3s
          tcpKeepalive:
            time: 60s
            interval: 10s
        http:
          idleTimeout: 0.030s
- apiVersion: networking.istio.io/v1beta1
  kind: DestinationRule
  metadata:
    name: postgres
    namespace: clair
  spec:
    host: postgres.clair.svc.cluster.local
    trafficPolicy:
      connectionPool:
        tcp:
          maxConnections: 100
          connectTimeout: 30s
          tcpKeepalive:
            time: 60s
            interval: 10s
- apiVersion: networking.istio.io/v1beta1
  kind: VirtualService
  metadata:
    name: clairv4
    namespace: clair
  spec:
    gateways:
    - istio-system/frontend-gateway
    hosts:
    - clairv4.clair.svc.cluster.local
    - clair.example.com
    http:
    - match:
      - uri:
          prefix: /metrics
      rewrite:
        uri: /metrics
      route:
      - destination:
          host: clairv4.clair.svc.cluster.local
          port:
            number: 8089
          subset: v1
        weight: 100
    - match:
      - uri:
          prefix: /
      route:
      - destination:
          host: clairv4.clair.svc.cluster.local
          port:
            number: 8080
          subset: v1
        weight: 100
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
