apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system
resources:
- namespace.yml
- deployment.yml

images:
- name: localhost/proxyv2
  newName: docker.io/istio/proxyv2
  newTag: "1.16.1"
- name: localhost/pilot
  newName: docker.io/istio/pilot
  newTag: "1.16.1"
